// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_table`, `escape_sql`, `get_config`, `global`, `make_batch`, `make_schema`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LanceConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

/// Initialise LanceDB at `db_path`.  Must be called once at app startup.
/// `embedding_dim` must match the model (nomic-embed-text → 768).
Future<void> initLanceDb({required String dbPath, required int embeddingDim}) =>
    RustLib.instance.api.crateApiInitLanceDb(
      dbPath: dbPath,
      embeddingDim: embeddingDim,
    );

/// Insert or replace a single embedding.
/// Delete-then-insert is LanceDB's upsert pattern.
Future<void> lanceUpsertEmbedding({
  required String sourceId,
  required String sourceType,
  required String modelName,
  required String contentHash,
  required List<double> vector,
}) => RustLib.instance.api.crateApiLanceUpsertEmbedding(
  sourceId: sourceId,
  sourceType: sourceType,
  modelName: modelName,
  contentHash: contentHash,
  vector: vector,
);

/// Remove the embedding for a given source item.
Future<void> lanceDeleteBySource({required String sourceId}) =>
    RustLib.instance.api.crateApiLanceDeleteBySource(sourceId: sourceId);

/// Return content_hash + model_name for a source item so the Dart side can
/// decide whether re-indexing is needed.
Future<SourceHashEntry?> lanceGetSourceHash({required String sourceId}) =>
    RustLib.instance.api.crateApiLanceGetSourceHash(sourceId: sourceId);

/// ANN vector search using cosine distance.
/// Returns up to `top_k` results sorted by similarity descending.
/// `filter_types` restricts to those source_type values (empty = all types).
Future<List<SimilarityResult>> lanceSearchSimilar({
  required List<double> queryVector,
  required int topK,
  required List<String> filterTypes,
}) => RustLib.instance.api.crateApiLanceSearchSimilar(
  queryVector: queryVector,
  topK: topK,
  filterTypes: filterTypes,
);

/// Return (source_id, source_type, content_hash, model_name) for all rows,
/// optionally filtered to one source_type.  Used for batch change-detection.
Future<List<SourceHashEntry>> lanceGetAllHashes({
  required String sourceTypeFilter,
}) => RustLib.instance.api.crateApiLanceGetAllHashes(
  sourceTypeFilter: sourceTypeFilter,
);

/// Stats for the VectorDB settings screen.
Future<VectorDbStats> lanceGetStats() =>
    RustLib.instance.api.crateApiLanceGetStats();

/// Build an IVF-PQ HNSW index on the vector column.
/// Requires ≥ 256 rows.  Dramatically speeds up ANN search at scale.
Future<void> lanceCreateVectorIndex() =>
    RustLib.instance.api.crateApiLanceCreateVectorIndex();

/// Drop and recreate the embeddings table (complete wipe).
Future<void> lanceDeleteAll() => RustLib.instance.api.crateApiLanceDeleteAll();

/// Returns true if init_lance_db has been called successfully.
Future<bool> lanceIsInitialized() =>
    RustLib.instance.api.crateApiLanceIsInitialized();

/// Return row counts grouped by source_type.  Used by the Collections tab.
Future<List<TypeCount>> lanceGetTypeCounts() =>
    RustLib.instance.api.crateApiLanceGetTypeCounts();

/// Return a page of embedding rows (no vector data) for the Browser tab.
/// `source_type_filter` — empty string means all types.
/// `offset` / `limit`  — for pagination.
Future<List<EmbeddingRow>> lanceGetRowsPage({
  required String sourceTypeFilter,
  required PlatformInt64 offset,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLanceGetRowsPage(
  sourceTypeFilter: sourceTypeFilter,
  offset: offset,
  limit: limit,
);

/// Delete all embeddings of a given source_type.  Used by the Collections tab.
Future<void> lanceDeleteByType({required String sourceType}) =>
    RustLib.instance.api.crateApiLanceDeleteByType(sourceType: sourceType);

/// A single embedding row with all metadata but *without* the vector bytes.
/// Used by the Browser tab — we never want to ship raw float arrays to Dart UI.
class EmbeddingRow {
  final String sourceId;
  final String sourceType;
  final String modelName;
  final String contentHash;
  final PlatformInt64 createdAt;

  const EmbeddingRow({
    required this.sourceId,
    required this.sourceType,
    required this.modelName,
    required this.contentHash,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      sourceType.hashCode ^
      modelName.hashCode ^
      contentHash.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbeddingRow &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          sourceType == other.sourceType &&
          modelName == other.modelName &&
          contentHash == other.contentHash &&
          createdAt == other.createdAt;
}

class SimilarityResult {
  final String sourceId;
  final String sourceType;

  /// Cosine similarity in [-1, 1].  LanceDB _distance = 1 - cosine_sim.
  final double similarity;
  final String contentHash;
  final String modelName;

  const SimilarityResult({
    required this.sourceId,
    required this.sourceType,
    required this.similarity,
    required this.contentHash,
    required this.modelName,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      sourceType.hashCode ^
      similarity.hashCode ^
      contentHash.hashCode ^
      modelName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimilarityResult &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          sourceType == other.sourceType &&
          similarity == other.similarity &&
          contentHash == other.contentHash &&
          modelName == other.modelName;
}

class SourceHashEntry {
  final String sourceId;
  final String sourceType;
  final String contentHash;
  final String modelName;

  const SourceHashEntry({
    required this.sourceId,
    required this.sourceType,
    required this.contentHash,
    required this.modelName,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      sourceType.hashCode ^
      contentHash.hashCode ^
      modelName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceHashEntry &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          sourceType == other.sourceType &&
          contentHash == other.contentHash &&
          modelName == other.modelName;
}

/// Per-source-type row count.  Used by the Collections tab.
class TypeCount {
  final String sourceType;
  final PlatformInt64 count;

  const TypeCount({required this.sourceType, required this.count});

  @override
  int get hashCode => sourceType.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypeCount &&
          runtimeType == other.runtimeType &&
          sourceType == other.sourceType &&
          count == other.count;
}

class VectorDbStats {
  final PlatformInt64 totalEmbeddings;
  final bool hasIndex;
  final String dbPath;
  final int embeddingDim;

  const VectorDbStats({
    required this.totalEmbeddings,
    required this.hasIndex,
    required this.dbPath,
    required this.embeddingDim,
  });

  @override
  int get hashCode =>
      totalEmbeddings.hashCode ^
      hasIndex.hashCode ^
      dbPath.hashCode ^
      embeddingDim.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VectorDbStats &&
          runtimeType == other.runtimeType &&
          totalEmbeddings == other.totalEmbeddings &&
          hasIndex == other.hasIndex &&
          dbPath == other.dbPath &&
          embeddingDim == other.embeddingDim;
}
