// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1451855313;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ai_vault_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiInitLanceDb({
    required String dbPath,
    required int embeddingDim,
  });

  Future<void> crateApiLanceCreateVectorIndex();

  Future<void> crateApiLanceDeleteAll();

  Future<void> crateApiLanceDeleteBySource({required String sourceId});

  Future<List<SourceHashEntry>> crateApiLanceGetAllHashes({
    required String sourceTypeFilter,
  });

  Future<SourceHashEntry?> crateApiLanceGetSourceHash({
    required String sourceId,
  });

  Future<VectorDbStats> crateApiLanceGetStats();

  Future<bool> crateApiLanceIsInitialized();

  Future<List<SimilarityResult>> crateApiLanceSearchSimilar({
    required List<double> queryVector,
    required int topK,
    required List<String> filterTypes,
  });

  Future<void> crateApiLanceUpsertEmbedding({
    required String sourceId,
    required String sourceType,
    required String modelName,
    required String contentHash,
    required List<double> vector,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiInitLanceDb({
    required String dbPath,
    required int embeddingDim,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_32(embeddingDim, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitLanceDbConstMeta,
        argValues: [dbPath, embeddingDim],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitLanceDbConstMeta => const TaskConstMeta(
    debugName: "init_lance_db",
    argNames: ["dbPath", "embeddingDim"],
  );

  @override
  Future<void> crateApiLanceCreateVectorIndex() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceCreateVectorIndexConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceCreateVectorIndexConstMeta =>
      const TaskConstMeta(debugName: "lance_create_vector_index", argNames: []);

  @override
  Future<void> crateApiLanceDeleteAll() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceDeleteAllConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceDeleteAllConstMeta =>
      const TaskConstMeta(debugName: "lance_delete_all", argNames: []);

  @override
  Future<void> crateApiLanceDeleteBySource({required String sourceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceDeleteBySourceConstMeta,
        argValues: [sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceDeleteBySourceConstMeta =>
      const TaskConstMeta(
        debugName: "lance_delete_by_source",
        argNames: ["sourceId"],
      );

  @override
  Future<List<SourceHashEntry>> crateApiLanceGetAllHashes({
    required String sourceTypeFilter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceTypeFilter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_source_hash_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceGetAllHashesConstMeta,
        argValues: [sourceTypeFilter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceGetAllHashesConstMeta => const TaskConstMeta(
    debugName: "lance_get_all_hashes",
    argNames: ["sourceTypeFilter"],
  );

  @override
  Future<SourceHashEntry?> crateApiLanceGetSourceHash({
    required String sourceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_source_hash_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceGetSourceHashConstMeta,
        argValues: [sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceGetSourceHashConstMeta => const TaskConstMeta(
    debugName: "lance_get_source_hash",
    argNames: ["sourceId"],
  );

  @override
  Future<VectorDbStats> crateApiLanceGetStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vector_db_stats,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceGetStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceGetStatsConstMeta =>
      const TaskConstMeta(debugName: "lance_get_stats", argNames: []);

  @override
  Future<bool> crateApiLanceIsInitialized() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLanceIsInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceIsInitializedConstMeta =>
      const TaskConstMeta(debugName: "lance_is_initialized", argNames: []);

  @override
  Future<List<SimilarityResult>> crateApiLanceSearchSimilar({
    required List<double> queryVector,
    required int topK,
    required List<String> filterTypes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(queryVector, serializer);
          sse_encode_i_32(topK, serializer);
          sse_encode_list_String(filterTypes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_similarity_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceSearchSimilarConstMeta,
        argValues: [queryVector, topK, filterTypes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceSearchSimilarConstMeta => const TaskConstMeta(
    debugName: "lance_search_similar",
    argNames: ["queryVector", "topK", "filterTypes"],
  );

  @override
  Future<void> crateApiLanceUpsertEmbedding({
    required String sourceId,
    required String sourceType,
    required String modelName,
    required String contentHash,
    required List<double> vector,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceId, serializer);
          sse_encode_String(sourceType, serializer);
          sse_encode_String(modelName, serializer);
          sse_encode_String(contentHash, serializer);
          sse_encode_list_prim_f_32_loose(vector, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanceUpsertEmbeddingConstMeta,
        argValues: [sourceId, sourceType, modelName, contentHash, vector],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceUpsertEmbeddingConstMeta =>
      const TaskConstMeta(
        debugName: "lance_upsert_embedding",
        argNames: [
          "sourceId",
          "sourceType",
          "modelName",
          "contentHash",
          "vector",
        ],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SourceHashEntry dco_decode_box_autoadd_source_hash_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_source_hash_entry(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SimilarityResult> dco_decode_list_similarity_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_similarity_result).toList();
  }

  @protected
  List<SourceHashEntry> dco_decode_list_source_hash_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_source_hash_entry).toList();
  }

  @protected
  SourceHashEntry? dco_decode_opt_box_autoadd_source_hash_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_source_hash_entry(raw);
  }

  @protected
  SimilarityResult dco_decode_similarity_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SimilarityResult(
      sourceId: dco_decode_String(arr[0]),
      sourceType: dco_decode_String(arr[1]),
      similarity: dco_decode_f_64(arr[2]),
      contentHash: dco_decode_String(arr[3]),
      modelName: dco_decode_String(arr[4]),
    );
  }

  @protected
  SourceHashEntry dco_decode_source_hash_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SourceHashEntry(
      sourceId: dco_decode_String(arr[0]),
      sourceType: dco_decode_String(arr[1]),
      contentHash: dco_decode_String(arr[2]),
      modelName: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VectorDbStats dco_decode_vector_db_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VectorDbStats(
      totalEmbeddings: dco_decode_i_64(arr[0]),
      hasIndex: dco_decode_bool(arr[1]),
      dbPath: dco_decode_String(arr[2]),
      embeddingDim: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SourceHashEntry sse_decode_box_autoadd_source_hash_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_source_hash_entry(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SimilarityResult> sse_decode_list_similarity_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SimilarityResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_similarity_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<SourceHashEntry> sse_decode_list_source_hash_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SourceHashEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_source_hash_entry(deserializer));
    }
    return ans_;
  }

  @protected
  SourceHashEntry? sse_decode_opt_box_autoadd_source_hash_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_source_hash_entry(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SimilarityResult sse_decode_similarity_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceId = sse_decode_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_similarity = sse_decode_f_64(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_modelName = sse_decode_String(deserializer);
    return SimilarityResult(
      sourceId: var_sourceId,
      sourceType: var_sourceType,
      similarity: var_similarity,
      contentHash: var_contentHash,
      modelName: var_modelName,
    );
  }

  @protected
  SourceHashEntry sse_decode_source_hash_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceId = sse_decode_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_modelName = sse_decode_String(deserializer);
    return SourceHashEntry(
      sourceId: var_sourceId,
      sourceType: var_sourceType,
      contentHash: var_contentHash,
      modelName: var_modelName,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VectorDbStats sse_decode_vector_db_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalEmbeddings = sse_decode_i_64(deserializer);
    var var_hasIndex = sse_decode_bool(deserializer);
    var var_dbPath = sse_decode_String(deserializer);
    var var_embeddingDim = sse_decode_i_32(deserializer);
    return VectorDbStats(
      totalEmbeddings: var_totalEmbeddings,
      hasIndex: var_hasIndex,
      dbPath: var_dbPath,
      embeddingDim: var_embeddingDim,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_source_hash_entry(
    SourceHashEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_source_hash_entry(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_similarity_result(
    List<SimilarityResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_similarity_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_source_hash_entry(
    List<SourceHashEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_source_hash_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_source_hash_entry(
    SourceHashEntry? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_source_hash_entry(self, serializer);
    }
  }

  @protected
  void sse_encode_similarity_result(
    SimilarityResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceId, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_f_64(self.similarity, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_String(self.modelName, serializer);
  }

  @protected
  void sse_encode_source_hash_entry(
    SourceHashEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceId, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_String(self.modelName, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vector_db_stats(
    VectorDbStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.totalEmbeddings, serializer);
    sse_encode_bool(self.hasIndex, serializer);
    sse_encode_String(self.dbPath, serializer);
    sse_encode_i_32(self.embeddingDim, serializer);
  }
}
